/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './center.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../auth/auth.service';
import * as import9 from '../bill/bill.service';
import * as import10 from '../friend/friend.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../bill/bill-list.component';
import * as import14 from '../bill/add-bill.component';
import * as import15 from '../bill/bill-list.component.ngfactory';
import * as import16 from '../bill/add-bill.component.ngfactory';
var renderType_CenterComponent_Host:import0.RenderComponentType = (null as any);
class _View_CenterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CenterComponent_0_4:import3.CenterComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CenterComponent_Host0,renderType_CenterComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-center-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CenterComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CenterComponent_0_4 = new import3.CenterComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.BillService),this.parentInjector.get(import10.FriendService));
    this._appEl_0.initComponent(this._CenterComponent_0_4,[],compView_0);
    compView_0.create(this._CenterComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CenterComponent) && (0 === requestNodeIndex))) { return this._CenterComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CenterComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CenterComponent_Host === (null as any))) { (renderType_CenterComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_CenterComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CenterComponentNgFactory:import12.ComponentFactory<import3.CenterComponent> = new import12.ComponentFactory<import3.CenterComponent>('app-center-component',viewFactory_CenterComponent_Host0,import3.CenterComponent);
const styles_CenterComponent:any[] = [];
var renderType_CenterComponent:import0.RenderComponentType = (null as any);
class _View_CenterComponent0 extends import1.AppView<import3.CenterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  /*private*/ _appEl_59:import2.AppElement;
  _BillListComponent_59_4:import13.BillListComponent;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _AddBillComponent_62_4:import14.AddBillComponent;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CenterComponent0,renderType_CenterComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-12');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'id','center_column');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','dashboard header');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','topbar');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'h1',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','actions');
    this._text_12 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','btn btn-large btn-orange');
    this.renderer.setElementAttribute(this._el_13,'data-toggle','modal');
    this._text_14 = this.renderer.createText(this._el_13,'\n                        Add a bill\n                    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','btn btn-large btn-mint');
    this.renderer.setElementAttribute(this._el_16,'data-toggle','modal');
    this.renderer.setElementAttribute(this._el_16,'href','#settle_up_form');
    this._text_17 = this.renderer.createText(this._el_16,'\n                        Settle up\n                    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','clearfix');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'id','dashboard_balances');
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','total_balances');
    this._text_27 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','block');
    this._text_29 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'div',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','block');
    this._text_35 = this.renderer.createText(this._el_34,'\n                        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'div',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','title');
    this._text_37 = this.renderer.createText(this._el_36,'\n                            you owe\n                        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n                        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_34,'span',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','neutral');
    this._text_40 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_34,'\n                    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','block');
    this._text_44 = this.renderer.createText(this._el_43,'\n                        ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','title');
    this._text_46 = this.renderer.createText(this._el_45,'\n                            you are owed\n                        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n                        ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_43,'span',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','neutral');
    this._text_49 = this.renderer.createText(this._el_48,'\n                        ',(null as any));
    this._text_50 = this.renderer.createText(this._el_43,'\n                    ',(null as any));
    this._text_51 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_52 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_56 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_57 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','col-md-12');
    this._text_58 = this.renderer.createText(this._el_57,'\n    ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'bill-list-component',(null as any));
    this._appEl_59 = new import2.AppElement(59,57,this,this._el_59);
    var compView_59:any = import15.viewFactory_BillListComponent0(this.viewUtils,this.injector(59),this._appEl_59);
    this._BillListComponent_59_4 = new import13.BillListComponent(this.parentInjector.get(import9.BillService),this.parentInjector.get(import10.FriendService));
    this._appEl_59.initComponent(this._BillListComponent_59_4,[],compView_59);
    compView_59.create(this._BillListComponent_59_4,[],(null as any));
    this._text_60 = this.renderer.createText(this._el_57,'\n',(null as any));
    this._text_61 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_62 = this.renderer.createElement(parentRenderNode,'add-bill-component',(null as any));
    this._appEl_62 = new import2.AppElement(62,(null as any),this,this._el_62);
    var compView_62:any = import16.viewFactory_AddBillComponent0(this.viewUtils,this.injector(62),this._appEl_62);
    this._AddBillComponent_62_4 = new import14.AddBillComponent(this.parentInjector.get(import9.BillService),this.parentInjector.get(import10.FriendService));
    this._appEl_62.initComponent(this._AddBillComponent_62_4,[],compView_62);
    compView_62.create(this._AddBillComponent_62_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.BillListComponent) && (59 === requestNodeIndex))) { return this._BillListComponent_59_4; }
    if (((token === import14.AddBillComponent) && (62 === requestNodeIndex))) { return this._AddBillComponent_62_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._BillListComponent_59_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AddBillComponent_62_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',(this.context.friendService.selectedFriend? this.context.friendService.selectedFriend.fName: ''),'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_9,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:boolean = !this.context.friendService.selectedFriend;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_13,'disabled',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onAddBill()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_CenterComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CenterComponent> {
  if ((renderType_CenterComponent === (null as any))) { (renderType_CenterComponent = viewUtils.createRenderComponentType('E:/ACADGILD/case study/splitter-angular2/assets/app/common/center.component.html',0,import11.ViewEncapsulation.None,styles_CenterComponent,{})); }
  return new _View_CenterComponent0(viewUtils,parentInjector,declarationEl);
}