/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './header.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../auth/auth.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link_active';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/router/src/router_state';
import * as import18 from '@angular/common/src/location/location_strategy';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/security';
var renderType_HeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import3.HeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import3.HeaderComponent(this.parentInjector.get(import8.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeaderComponent_Host === (null as any))) { (renderType_HeaderComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_HeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeaderComponentNgFactory:import10.ComponentFactory<import3.HeaderComponent> = new import10.ComponentFactory<import3.HeaderComponent>('app-header',viewFactory_HeaderComponent_Host0,import3.HeaderComponent);
const styles_HeaderComponent:any[] = [];
var renderType_HeaderComponent:import0.RenderComponentType = (null as any);
class _View_HeaderComponent0 extends import1.AppView<import3.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkActive_9_3:import11.RouterLinkActive;
  _query_RouterLink_9_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_9_1:import12.QueryList<any>;
  _el_10:any;
  _RouterLinkWithHref_10_3:import13.RouterLinkWithHref;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _RouterLinkActive_13_3:import11.RouterLinkActive;
  _query_RouterLink_13_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_13_1:import12.QueryList<any>;
  _el_14:any;
  _RouterLinkWithHref_14_3:import13.RouterLinkWithHref;
  _text_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import14.NgIf;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import14.NgIf;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import14.NgIf;
  _text_24:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _arr_1:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent0,renderType_HeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'header',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this.renderer.setElementAttribute(this._el_0,'style','background-color:#9d9d9d');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-md-3');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','col-md-7');
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','nav nav-pills pull-right');
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'li',(null as any));
    this.renderer.setElementAttribute(this._el_9,'routerLinkActive','active');
    this._RouterLinkActive_9_3 = new import11.RouterLinkActive(this.parentInjector.get(import15.Router),new import16.ElementRef(this._el_9),this.renderer);
    this._query_RouterLink_9_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_9_1 = new import12.QueryList<any>();
    this._el_10 = this.renderer.createElement(this._el_9,'a',(null as any));
    this._RouterLinkWithHref_10_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._text_11 = this.renderer.createText(this._el_10,'Home',(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_7,'li',(null as any));
    this.renderer.setElementAttribute(this._el_13,'routerLinkActive','active');
    this._RouterLinkActive_13_3 = new import11.RouterLinkActive(this.parentInjector.get(import15.Router),new import16.ElementRef(this._el_13),this.renderer);
    this._query_RouterLink_13_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_13_1 = new import12.QueryList<any>();
    this._el_14 = this.renderer.createElement(this._el_13,'a',(null as any));
    this._RouterLinkWithHref_14_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._text_15 = this.renderer.createText(this._el_14,'Signup',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_17 = new import2.AppElement(17,7,this,this._anchor_17);
    this._TemplateRef_17_5 = new import19.TemplateRef_(this._appEl_17,viewFactory_HeaderComponent1);
    this._NgIf_17_6 = new import14.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_19 = new import2.AppElement(19,7,this,this._anchor_19);
    this._TemplateRef_19_5 = new import19.TemplateRef_(this._appEl_19,viewFactory_HeaderComponent2);
    this._NgIf_19_6 = new import14.NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_23 = new import2.AppElement(23,0,this,this._anchor_23);
    this._TemplateRef_23_5 = new import19.TemplateRef_(this._appEl_23,viewFactory_HeaderComponent3);
    this._NgIf_23_6 = new import14.NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._arr_1 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkWithHref_10_3; }
    if (((token === import11.RouterLinkActive) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkActive_9_3; }
    if (((token === import13.RouterLinkWithHref) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkWithHref_14_3; }
    if (((token === import11.RouterLinkActive) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkActive_13_3; }
    if (((token === import19.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import14.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import19.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import14.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6; }
    if (((token === import19.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import14.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_9_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_9_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_2:any = this._arr_0('/home');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_10_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_10_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_4:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkActive_13_3.routerLinkActive = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_13_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_6:any = this._arr_1('/signup');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._RouterLinkWithHref_14_3.routerLink = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_14_3.ngOnChanges(changes); }
    const currVal_8:boolean = !this.context.authService.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_17_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.context.authService.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_19_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.authService.getLoggedInUserName();
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_23_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_9_0.dirty) {
        this._query_RouterLink_9_0.reset([]);
        this._RouterLinkActive_9_3.links = this._query_RouterLink_9_0;
        this._query_RouterLink_9_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_9_1.dirty) {
        this._query_RouterLinkWithHref_9_1.reset([this._RouterLinkWithHref_10_3]);
        this._RouterLinkActive_9_3.linksWithHrefs = this._query_RouterLinkWithHref_9_1;
        this._query_RouterLinkWithHref_9_1.notifyOnChanges();
      }
      if (this._query_RouterLink_13_0.dirty) {
        this._query_RouterLink_13_0.reset([]);
        this._RouterLinkActive_13_3.links = this._query_RouterLink_13_0;
        this._query_RouterLink_13_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_13_1.dirty) {
        this._query_RouterLinkWithHref_13_1.reset([this._RouterLinkWithHref_14_3]);
        this._RouterLinkActive_13_3.linksWithHrefs = this._query_RouterLinkWithHref_13_1;
        this._query_RouterLinkWithHref_13_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_9_3.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_13_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._RouterLinkWithHref_10_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_10,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._RouterLinkWithHref_14_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_14,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_7));
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_10_3.ngOnDestroy();
    this._RouterLinkActive_9_3.ngOnDestroy();
    this._RouterLinkWithHref_14_3.ngOnDestroy();
    this._RouterLinkActive_13_3.ngOnDestroy();
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_10_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_14_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HeaderComponent> {
  if ((renderType_HeaderComponent === (null as any))) { (renderType_HeaderComponent = viewUtils.createRenderComponentType('E:/ACADGILD/case study/splitter-angular2/assets/app/common/header.component.html',0,import9.ViewEncapsulation.None,styles_HeaderComponent,{})); }
  return new _View_HeaderComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent1 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import11.RouterLinkActive;
  _query_RouterLink_0_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import12.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _text_2:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent1,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'routerLinkActive','active');
    this._RouterLinkActive_0_3 = new import11.RouterLinkActive(this.parent.parentInjector.get(import15.Router),new import16.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import12.QueryList<any>();
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import15.Router),this.parent.parentInjector.get(import17.ActivatedRoute),this.parent.parentInjector.get(import18.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'Sign in',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import11.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_0_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_2:any = this._arr_0('/signin');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset([]);
        this._RouterLinkActive_0_3.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_0_3.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent2 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import11.RouterLinkActive;
  _query_RouterLink_0_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import12.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import13.RouterLinkWithHref;
  _text_2:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent2,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'routerLinkActive','active');
    this._RouterLinkActive_0_3 = new import11.RouterLinkActive(this.parent.parentInjector.get(import15.Router),new import16.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import12.QueryList<any>();
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import15.Router),this.parent.parentInjector.get(import17.ActivatedRoute),this.parent.parentInjector.get(import18.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'Logout',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import11.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_0_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_2:any = this._arr_0('/logout');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset([]);
        this._RouterLinkActive_0_3.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_0_3.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent3,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',('Welcome ' + this.parent.context.authService.getLoggedInUserName()),'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeaderComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent3(viewUtils,parentInjector,declarationEl);
}